const userTypes = {
    SIGN_IN_WITH_GOOGLE : 'SIGN_IN_WITH_GOOGLE',
    SIGN_IN_WITH_FACEBOOK: 'SIGN_IN_WITH_FACEBOOK',

    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_START : 'EMAIL_SIGN_IN_START',
    USER_ERROR: 'USER_ERROR',
    RESET_ERROR : 'RESET_ERROR',


    SIGN_UP_USER : 'SIGN_UP_USER'
}
export default userTypes;